name: "Tests"

on:
  pull_request:

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  # AWS_REGION: ${{ secrets.AWS_REGION }}

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        version: [14, 16, 18]

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js ${{ matrix.version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.version }}
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'

      - name: Install
        id: install
        run: |
          npm ci

      - name: Tests
        run: |
          npm run test
